### ISSUE TITLE
Hi :-)

### ISSUE THREAD

**Issue by perguth** [pguth/messages#7]
@Ivkaa, I am just thinking about a new project and was remembered of you. I found that sweet and wanted to tell you. Thanks for having been there! ✨

**Comment by perguth** [comment]
If you'd like I'd invite you to a hackmd that I am working on right now. Text me in Signal (*brr*) on that.

**Comment by perguth** [comment]
AAAAAaaand there it is: https://hackmd.io/s/SyXrZoTEG 🚀

**Comment by perguth** [comment]
Funny 🦊 So similar in sound I mixed those two words up... Is "Ivkaa" a variation of "Ivanka" somehow? I wonder if those two are connected semantically somehow. ![image](https://user-images.githubusercontent.com/85259/35081112-35e9523c-fc12-11e7-9559-90d8c82c47ad.png)

**Comment by Ivkaa** [comment]
Hello! sure, I'd love to hear about your project :) I cannot search by username on signal afaik, just by number, but do you have also Wire or Threema?

**Comment by Ivkaa** [comment]
And yeah, it's same name! Ivka/Ivana/Ivanka are all the same

**Comment by perguth** [comment]
That's me: +49 711 217 244 42
